catagories = {
	'aliexpress': 'Shopping',
	'AMZN': 'Shopping',
    'AMAZON': 'Shopping',
    'Apple': 'Phone Bills',
    'Apple NZ GCS           SYDNEY        NSW': 'Phone Bills',
    'AT HOP AUCKLAND': 'Travel Expenses',
    'AT PARKING': 'Travel Expenses',
	'Ava Chi': 'Eating Out',
	'Avachi Midcity': 'Eating Out',
	'Bailey Nelson': 'Health',
    'BP': 'Travel Expenses',
	'Bunnings': 'Shopping',
	'Burgerfuel': 'Eating Out',
    'Briscoes': 'Shopping',
    'Bunnings': 'Shopping',
    'Carls Jr': 'Eating Out',
	'Coffee Club': 'Eating Out',
	'Countdown': 'Groceries',
	'Dollar Outlet': 'Shopping',
	'Don Don': 'Eating Out',
	'Dunkin Donuts': 'Coffee',
    'EIG*HOSTGATOR': 'Annual Bills',
	'Foreign Currency Fee': 'Fees',
	'Good Fellas': 'Health',
	'H&M': 'Shopping',
	'Hollywood Cafe Al 19': 'Coffee',
	'iHerb': 'Health',
    'iTunes': 'App Shopping',
	'Jaycar': 'Shopping',
    'Katsubi': 'Eating Out',
	'Krispy Kreme': 'Coffee',
	'Krispy Kreme           Auckland      Auc': 'Coffee',
    'KMart': 'Shopping',
	'McDonald': 'Eating Out',
	'Mobil': 'Travel Expense',
	'Mojo': 'Coffee',
	'Munchy Mart': 'Eating Out',
	'Nando': 'Eating Out',
    'Noel Leeming': 'Shopping',
	'Night\'n Day': 'Eating Out',
	'Pak N Save': 'Groceries',
	'Paknsave': 'Groceries',
    'Payless supplements': 'Health',
	'PB Tech': 'Shopping',
	'Pizza': 'Eating Out',
	'Push Developments': 'Eating Out',
    'Rattan': 'Groceries',
	'Relax Lounge': 'Coffee',
	'Repco': 'Travel Expense',
	'Sals': 'Eating Out',
	'Shaky Isles': 'Eating Out',
    'Skinny': 'Phone Bills',
    'SKINNY                 AUCKLAND      NZL': 'Phone Bills',
    'Spotify': 'Phone Bills',
	'Subway': 'Eating Out',
	'The Barber Shop': 'Health',
	'The Coffee Shop': 'Coffee',
    'The Coffee Club': 'Coffee',
    'TWL': 'Shopping',
    'Unichem': 'Health',
	'Wilson Parking': 'Travel Expences',
	'Z': 'Travel Expense'
}

exclude = [
	'AUTOMATIC PAYMENT',
	'ONLINE BANKING',
	'BILL PAYMENT'
]
